#!/bin/bash

#PBS -q gerstein -Wgroup_list=gerstein
#PBS -m abe -M brian.barron@yale.edu
#PBS -l nodes=1:ppn=8 -W PARTITION:m610

#####
#	Expression_Analysis.pbs - This script will gather relevant expression information from RSEM output files
#####

#####Assign Global Variables: the expression folder (where STAR_RSEM output files can be found) and output folder (where analysis file will be written)
expression_folder="/gpfs/scratch/fas/gerstein/ky26/ky26_brian/Chupp_RNA-seq_Controls/Aligned_Reads/Single_End"
output_folder="/gpfs/scratch/fas/gerstein/ky26/ky26_brian/Chupp_RNA-seq_Controls/Expression_Data/Single_End"
mkdir $output_folder

#Initiate for loop F to detect sample folders and extract relevant info (name, # reads, % unique map to genome, % map to transcriptome, and % unique map to transcriptome)
cd $expression_folder

for F in *aligned; do
  cd $F
  #echo $F > $output_folder/${F}_stats.txt
  #cut -f 6 Quant.genes.results | grep '[1-9]\+' | wc -l >> $output_folder/${F}_stats.txt
  echo $F > $output_folder/${F}_name.txt
  cut -f 6 Quant.genes.results > $output_folder/${F}_tpm.txt 
  cd $expression_folder
done

#Combine TPM data into one large file
cd $output_folder

expression_file=$output_folder"/Expression_Analysis.txt"
touch $expression_file

for S in *tpm.txt; do
  cut -f 1 $S | paste $expression_file - > dummy.txt
	rm $expression_file
	mv ./dummy.txt $expression_file
done

#Combine names into one large file
name_file=$output_folder"/Sample_Names.txt"
touch $name_file

for T in *name.txt; do
        cut -f 1 $T | paste $name_file - > dummy.txt
        rm $name_file
        mv ./dummy.txt $name_file
done
